// Pre-loaded trivia questions for June 29 – July 3, 2026
// Each day: 3 questions, difficulty 1=easy, 2=medium, 3=hard
// Load these into Airtable TriviaQuestions table before launch
// Fields: Date (YYYY-MM-DD), Question, OptionA, OptionB, OptionC, OptionD, CorrectAnswer (A/B/C/D), Difficulty (1/2/3)

export const TRIVIA_BANK = [
  // --- June 29 ---
  {
    Date: '2026-06-29',
    Difficulty: 1,
    Question: 'In what year did the United States declare independence?',
    OptionA: '1774',
    OptionB: '1776',
    OptionC: '1781',
    OptionD: '1789',
    CorrectAnswer: 'B',
  },
  {
    Date: '2026-06-29',
    Difficulty: 2,
    Question: 'How many stars are on the current United States flag?',
    OptionA: '48',
    OptionB: '49',
    OptionC: '50',
    OptionD: '52',
    CorrectAnswer: 'C',
  },
  {
    Date: '2026-06-29',
    Difficulty: 3,
    Question: 'Which state was the last to be admitted to the Union, completing the 50-star flag?',
    OptionA: 'Alaska',
    OptionB: 'Hawaii',
    OptionC: 'New Mexico',
    OptionD: 'Arizona',
    CorrectAnswer: 'B',
  },

  // --- June 30 ---
  {
    Date: '2026-06-30',
    Difficulty: 1,
    Question: 'What document begins with the words "We the People"?',
    OptionA: 'The Declaration of Independence',
    OptionB: 'The Bill of Rights',
    OptionC: 'The Constitution',
    OptionD: 'The Emancipation Proclamation',
    CorrectAnswer: 'C',
  },
  {
    Date: '2026-06-30',
    Difficulty: 2,
    Question: 'Who was the first President of the United States?',
    OptionA: 'John Adams',
    OptionB: 'Benjamin Franklin',
    OptionC: 'Thomas Jefferson',
    OptionD: 'George Washington',
    CorrectAnswer: 'D',
  },
  {
    Date: '2026-06-30',
    Difficulty: 3,
    Question: 'In 2026, the United States celebrates 250 years of independence. What term describes this milestone anniversary?',
    OptionA: 'Bicentennial',
    OptionB: 'Semiquincentennial',
    OptionC: 'Tercentennial',
    OptionD: 'Jubilee',
    CorrectAnswer: 'B',
  },

  // --- July 1 ---
  {
    Date: '2026-07-01',
    Difficulty: 1,
    Question: 'How many stripes are on the United States flag?',
    OptionA: '13',
    OptionB: '15',
    OptionC: '50',
    OptionD: '12',
    CorrectAnswer: 'A',
  },
  {
    Date: '2026-07-01',
    Difficulty: 2,
    Question: 'Which city served as the first capital of the United States?',
    OptionA: 'Philadelphia',
    OptionB: 'Boston',
    OptionC: 'New York City',
    OptionD: 'Washington, D.C.',
    CorrectAnswer: 'C',
  },
  {
    Date: '2026-07-01',
    Difficulty: 3,
    Question: 'Which founding father is credited with writing the first draft of the Declaration of Independence?',
    OptionA: 'John Adams',
    OptionB: 'Benjamin Franklin',
    OptionC: 'James Madison',
    OptionD: 'Thomas Jefferson',
    CorrectAnswer: 'D',
  },

  // --- July 2 ---
  {
    Date: '2026-07-02',
    Difficulty: 1,
    Question: 'What is the national bird of the United States?',
    OptionA: 'Turkey',
    OptionB: 'Bald Eagle',
    OptionC: 'Golden Eagle',
    OptionD: 'Great Horned Owl',
    CorrectAnswer: 'B',
  },
  {
    Date: '2026-07-02',
    Difficulty: 2,
    Question: 'How many original colonies became the first United States?',
    OptionA: '12',
    OptionB: '13',
    OptionC: '14',
    OptionD: '15',
    CorrectAnswer: 'B',
  },
  {
    Date: '2026-07-02',
    Difficulty: 3,
    Question: 'The Star-Spangled Banner was written after the bombardment of which fort during the War of 1812?',
    OptionA: 'Fort Sumter',
    OptionB: 'Fort Ticonderoga',
    OptionC: 'Fort McHenry',
    OptionD: 'Fort Monroe',
    CorrectAnswer: 'C',
  },

  // --- July 3 ---
  {
    Date: '2026-07-03',
    Difficulty: 1,
    Question: 'What holiday does the United States celebrate on July 4th?',
    OptionA: 'Presidents Day',
    OptionB: 'Constitution Day',
    OptionC: 'Independence Day',
    OptionD: 'Veterans Day',
    CorrectAnswer: 'C',
  },
  {
    Date: '2026-07-03',
    Difficulty: 2,
    Question: 'The Liberty Bell is located in which U.S. city?',
    OptionA: 'Boston, MA',
    OptionB: 'Washington, D.C.',
    OptionC: 'New York City, NY',
    OptionD: 'Philadelphia, PA',
    CorrectAnswer: 'D',
  },
  {
    Date: '2026-07-03',
    Difficulty: 3,
    Question: 'Which amendment to the Constitution abolished slavery in the United States?',
    OptionA: '13th Amendment',
    OptionB: '14th Amendment',
    OptionC: '15th Amendment',
    OptionD: '19th Amendment',
    CorrectAnswer: 'A',
  },
]

export const SPIRIT_WEEK = [
  {
    date: '2026-06-29',
    day: 'Monday',
    theme: 'Red, White & Blue Day',
    description: 'The classic opener! Wear your patriotic colors — any combination of red, white, and blue counts.',
    icon: 'ti-flag',
  },
  {
    date: '2026-06-30',
    day: 'Tuesday',
    theme: 'Decade of America Day',
    description: 'Dress as any era of American history — flapper, \'50s diner, \'70s disco, \'80s neon, you name it!',
    icon: 'ti-clock-hour-4',
  },
  {
    date: '2026-07-01',
    day: 'Wednesday',
    theme: 'Patriotic Hats & Accessories Day',
    description: 'Wear your regular clothes but go wild with the headwear and accessories. The bigger, the better.',
    icon: 'ti-hat',
  },
  {
    date: '2026-07-02',
    day: 'Thursday',
    theme: 'Vintage Americana / Denim & Flannel Day',
    description: 'Lumberjack, cowboy, farmstead — channel your inner heartland American. Denim encouraged!',
    icon: 'ti-shirt',
  },
  {
    date: '2026-07-03',
    day: 'Friday',
    theme: 'Stars & Stripes Everything — Full Costume Day!',
    description: 'The grand finale. Go ALL out. Full patriotic costume encouraged. People\'s Choice winner announced today!',
    icon: 'ti-star',
  },
]
